# Generated by Django 5.2.4 on 2025-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflowrecord",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="status",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
